import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  English: {
    appName: "BhoomiRakshak",
    tagline: "AI Landslide Sentinel • NER",
    telemetryActive: "NER Telemetry: Active Monitoring • 8 States",
    gatewayConnected: "Gateway: Connected",
    gatewayReconnecting: "Gateway: Reconnecting...",
    sync: "Sync",
    refresh: "Refresh",
    commandDeck: "Command Deck",
    gisMap: "GIS Map",
    earlyWarning: "Early Warning",
    fieldReview: "Field Review",
    citizenPortal: "Citizen Portal",
    fieldApp: "Field Officer App",
    settings: "Settings",
    dbExplorer: "Database Explorer",
    signIn: "Sign In",
    signOut: "Sign Out",
    threatLevel: "Composite Threat Level",
    activeAlerts: "Active Emergency Alerts",
    criticalSectors: "Critical Risk Sectors",
    monitoredDistricts: "Monitored Districts",
    evacuationDirective: "Immediate Evacuation Advisory",
    rainfallTelemetry: "24h Accumulated Rainfall",
    recentAlerts: "Recent Multi-Channel Alerts",
    monitoredHotspots: "Monitored Landslide Hotspots",
    noActiveAlerts: "No active alerts in registry",
    safeThresholds: "Hydrometeorological and slope movement thresholds are normal.",
    submitReport: "Submit Hazard Report",
    selectDistrict: "Select Your District:",
    allDistricts: "All Monitored Districts (8 NER States)",
    severity: "Severity",
    critical: "CRITICAL",
    high: "HIGH",
    moderate: "MODERATE",
    low: "LOW",
    broadcastAlert: "Broadcast Multi-Channel Alert",
    priority1Title: "Priority Tier 1: 8 Field Masters",
    priority2Title: "Priority Tier 2: Registered Citizens",
    emailAlerts: "Institutional Email Alerts",
    smsBroadcast: "Emergency SMS Gateway",
    webRiskAlert: "Web App Risk Notification",
    dispatchedSuccess: "Alert Successfully Broadcasted Across Priority Channels"
  },
  Hindi: {
    appName: "भूमि रक्षक",
    tagline: "एआई भूस्खलन संवेदक • पूर्वोत्तर क्षेत्र",
    telemetryActive: "पूर्वोत्तर टेलीमेट्री: सक्रिय निगरानी • 8 राज्य",
    gatewayConnected: "गेटवे: जुड़ा हुआ है",
    gatewayReconnecting: "गेटवे: पुनः जुड़ रहा है...",
    sync: "सिंक",
    refresh: "ताज़ा करें",
    commandDeck: "कमांड डेक",
    gisMap: "जीआईएस नक्शा",
    earlyWarning: "पूर्व चेतावनी",
    fieldReview: "फील्ड रिपोर्ट समीक्षा",
    citizenPortal: "नागरिक पोर्टल",
    fieldApp: "फील्ड अधिकारी ऐप",
    settings: "प्रणाली सेटिंग्स",
    dbExplorer: "डेटाबेस एक्सप्लोरर",
    signIn: "लॉग इन करें",
    signOut: "लॉग आउट करें",
    threatLevel: "समग्र जोखिम स्तर",
    activeAlerts: "सक्रिय आपातकालीन अलर्ट",
    criticalSectors: "गंभीर जोखिम क्षेत्र",
    monitoredDistricts: "निगरानी वाले जिले",
    evacuationDirective: "तत्काल निकासी सलाह",
    rainfallTelemetry: "24 घंटे संचित वर्षा",
    recentAlerts: "हालिया बहु-चैनल अलर्ट",
    monitoredHotspots: "निगरानी किए गए भूस्खलन हॉटस्पॉट",
    noActiveAlerts: "रजिस्ट्री में कोई सक्रिय अलर्ट नहीं",
    safeThresholds: "वर्षा और ढलान की स्थिति सामान्य सीमाओं के भीतर है।",
    submitReport: "खतरे की रिपोर्ट दर्ज करें",
    selectDistrict: "अपना जिला चुनें:",
    allDistricts: "सभी 8 पूर्वोत्तर जिले",
    severity: "गंभीरता",
    critical: "अत्यंत गंभीर (CRITICAL)",
    high: "उच्च (HIGH)",
    moderate: "मध्यम (MODERATE)",
    low: "कम (LOW)",
    broadcastAlert: "आपातकालीन अलर्ट प्रसारित करें",
    priority1Title: "प्राथमिकता स्तर 1: 8 फील्ड कमांडर",
    priority2Title: "प्राथमिकता स्तर 2: पंजीकृत नागरिक",
    emailAlerts: "संस्थागत ईमेल अलर्ट",
    smsBroadcast: "आपातकालीन एसएमएस गेटवे",
    webRiskAlert: "वेब ऐप जोखिम सूचना",
    dispatchedSuccess: "प्राथमिकता चैनलों पर अलर्ट सफलतापूर्वक प्रसारित हुआ"
  },
  Assamese: {
    appName: "ভূমিৰক্ষক",
    tagline: "এআই ভূমিস্খলন প্ৰহৰী • উত্তৰ-পূৰ্বাঞ্চল",
    telemetryActive: "উত্তৰ-পূব টেলিমেট্ৰি: সক্ৰিয় নিৰীক্ষণ • ৮খন ৰাজ্য",
    gatewayConnected: "গেটৱে: সংযোজিত",
    gatewayReconnecting: "গেটৱে: পুনৰ সংযোগ হৈ আছে...",
    sync: "সময় সংমিশ্ৰণ",
    refresh: "নতুনকৈ লোড কৰক",
    commandDeck: "কমাণ্ড ডেক",
    gisMap: "জিআইএছ মানচিত্ৰ",
    earlyWarning: "আগতীয়া সতৰ্কবাণী",
    fieldReview: "ক্ষেত্ৰ প্ৰতিবেদন পৰ্যালোচনা",
    citizenPortal: "ৰাইজৰ প’ৰ্টেল",
    fieldApp: "ক্ষেত্ৰ বিষয়াৰ এপ",
    settings: "ব্যৱস্থা সংহতি",
    dbExplorer: "তথ্যকোষ পৰিদৰ্শক",
    signIn: "প্ৰৱেশ কৰক",
    signOut: "প্ৰস্থান কৰক",
    threatLevel: "সামগ্ৰিক বিপদৰ মাত্ৰা",
    activeAlerts: "সক্ৰিয় জৰুৰী সতৰ্কবাণী",
    criticalSectors: "সংকটজনক বিপদ খণ্ডসমূহ",
    monitoredDistricts: "নিৰীক্ষণ কৰা জিলাসমূহ",
    evacuationDirective: "অবিলম্বে আঁতৰি যোৱাৰ নিৰ্দেশনা",
    rainfallTelemetry: "২৪ ঘণ্টাৰ বৰষুণৰ পৰিমাণ",
    recentAlerts: "শেহতীয়া বহু-চেনেল সতৰ্কবাণী",
    monitoredHotspots: "চিহ্নিত ভূমিস্খলন স্থানসমূহ",
    noActiveAlerts: "পঞ্জীত কোনো সক্ৰিয় সতৰ্কবাণী নাই",
    safeThresholds: "বৰষুণ আৰু পাহাৰীয়া ঢালৰ অৱস্থা বৰ্তমান স্বাভাৱিক সীমাত আছে।",
    submitReport: "বিপদৰ প্ৰতিবেদন দাখিল কৰক",
    selectDistrict: "আপোনাৰ জিলা বাছক:",
    allDistricts: "সকলো ৮খন উত্তৰ-পূব জিলা",
    severity: "তীব্ৰতা",
    critical: "অতি সংকটজনক (CRITICAL)",
    high: "উচ্চ (HIGH)",
    moderate: "মধ্যম (MODERATE)",
    low: "নিম্ন (LOW)",
    broadcastAlert: "জৰুৰী সতৰ্কবাণী প্ৰচাৰ কৰক",
    priority1Title: "প্ৰাথমিক শ্ৰেণী ১: ৮ জন ফিল্ড মাষ্টাৰ/কমাণ্ডাৰ",
    priority2Title: "প্ৰাথমিক শ্ৰেণী ২: পঞ্জীভুক্ত নাগৰিকসকল",
    emailAlerts: "প্ৰাতিষ্ঠানিক ইমেইল সতৰ্কবাণী",
    smsBroadcast: "জৰুৰী এছএমএছ সেৱা",
    webRiskAlert: "ৱেব এপৰ বিপদ জাননী",
    dispatchedSuccess: "সকলো প্ৰাথমিক চেনেলত সতৰ্কবাণী সফলভাৱে প্ৰচাৰ কৰা হ’ল"
  },
  Bengali: {
    appName: "ভূমিরক্ষক",
    tagline: "এআই ভূমিধস সতর্কীকরণ • উত্তর-পূর্বাঞ্চল",
    telemetryActive: "টেলিমেট্রি সক্রিয়: ৮টি উত্তর-পূর্ব রাজ্য",
    gatewayConnected: "গেটওয়ে: সংযুক্ত",
    gatewayReconnecting: "গেটওয়ে: পুনরায় সংযোগ হচ্ছে...",
    sync: "সিঙ্ক",
    refresh: "রিফ্রেশ করুন",
    commandDeck: "কমান্ড ডেক",
    gisMap: "জিআইএস মানচিত্র",
    earlyWarning: "পূর্বাভাস ও সতর্কতা",
    fieldReview: "মাঠ পর্যায়ের প্রতিবেদন",
    citizenPortal: "নাগরিক পোর্টাল",
    fieldApp: "ফিল্ড অফিসার অ্যাপ",
    settings: "সেটিংস",
    dbExplorer: "ডাটাবেস এক্সপ্লোরার",
    signIn: "লগ ইন",
    signOut: "লগ আউট",
    threatLevel: "সম্মিলিত ঝুঁকি স্তর",
    activeAlerts: "সক্রিয় জরুরী সতর্কতা",
    criticalSectors: "সংকটপূর্ণ ঝুঁকি অঞ্চল",
    monitoredDistricts: "নজরদারিভুক্ত জেলা",
    evacuationDirective: "অবিলম্বে নিরাপদ স্থানে সরার নির্দেশ",
    rainfallTelemetry: "২৪ ঘণ্টার বৃষ্টিপাত",
    recentAlerts: "সাম্প্রতিক মাল্টি-চ্যানেল সতর্কতা",
    monitoredHotspots: "নজরদারিকৃত ভূমিধস প্রবণ অঞ্চল",
    noActiveAlerts: "বর্তমানে কোনো সক্রিয় সতর্কতা নেই",
    safeThresholds: "বৃষ্টিপাত এবং ঢাল আন্দোলন নিরাপদ সীমার মধ্যে রয়েছে।",
    submitReport: "বিপদের তথ্য জমা দিন",
    selectDistrict: "জেলা নির্বাচন করুন:",
    allDistricts: "সকল ৮টি উত্তর-পূর্বাঞ্চলীয় জেলা",
    severity: "তীব্রতা",
    critical: "চরম সংকটপূর্ণ (CRITICAL)",
    high: "উচ্চ (HIGH)",
    moderate: "মাঝারি (MODERATE)",
    low: "স্বাভাবিক (LOW)",
    broadcastAlert: "জরুরী সতর্কতা সম্প্রচার করুন",
    priority1Title: "অগ্রাধিকার স্তর ১: ৮ জন ফিল্ড কমান্ডার",
    priority2Title: "অগ্রাধিকার স্তর ২: নিবন্ধিত নাগরিকবৃন্দ",
    emailAlerts: "প্রাতিষ্ঠানিক ইমেইল সতর্কতা",
    smsBroadcast: "জরুরী এসএমএস গেটওয়ে",
    webRiskAlert: "ওয়েব অ্যাপ ঝুঁকি বিজ্ঞপ্তি",
    dispatchedSuccess: "অগ্রাধিকার ভিত্তিতে সতর্কতা সফলভাবে সম্প্রচারিত হয়েছে"
  },
  Mizo: {
    appName: "BhoomiRakshak",
    tagline: "AI Leimin Vengtu • NER",
    telemetryActive: "NER Telemetry: Enzui Mek • State 8",
    gatewayConnected: "Gateway: Inthlun Zawm A Ni",
    gatewayReconnecting: "Gateway: Inthlun leh mek...",
    sync: "Sync",
    refresh: "Tihtharlam",
    commandDeck: "Command Deck",
    gisMap: "GIS Map",
    earlyWarning: "Hriattirna Hma",
    fieldReview: "Hmun Hma Report",
    citizenPortal: "Mipuite Portal",
    fieldApp: "Field Officer App",
    settings: "Settings",
    dbExplorer: "Database Enna",
    signIn: "Lut Rawh",
    signOut: "Chhuak Rawh",
    threatLevel: "Hlauhawm Dinhmun",
    activeAlerts: "Hriattirna Hmanhmawh",
    criticalSectors: "Hmun Hlauhawm Zualte",
    monitoredDistricts: "District Enzuite",
    evacuationDirective: "Insaseng Tura Hriattirna",
    rainfallTelemetry: "Darkar 24 Ruahsur Zât",
    recentAlerts: "Hriattirna Chhuak Tharte",
    monitoredHotspots: "Leimin Hlauhawm Hmun",
    noActiveAlerts: "Tun dinhmunah hriattirna a awm lo",
    safeThresholds: "Ruahsur leh lei chetna dinhmun a la tha tawk e.",
    submitReport: "Hlauhawm Report Rawh",
    selectDistrict: "I District Thlang Rawh:",
    allDistricts: "NER District zawng zawng (8)",
    severity: "Hlauhawm Dan",
    critical: "HLAUHAWM ZUAL (CRITICAL)",
    high: "SANG (HIGH)",
    moderate: "LAIHMAWR (MODERATE)",
    low: "HNIAM (LOW)",
    broadcastAlert: "Hriattirna Puan Chhuahna",
    priority1Title: "Priority 1: Field Commander 8-te",
    priority2Title: "Priority 2: Mipui Inziah Lûtte",
    emailAlerts: "Email Hriattirna",
    smsBroadcast: "SMS Hmanhmawh",
    webRiskAlert: "Web App Hriattirna",
    dispatchedSuccess: "Hriattirna Hlawhtling Takin Puan Chhuah A Ni"
  },
  Khasi: {
    appName: "BhoomiRakshak",
    tagline: "AI Nongap Khyllem Khyndew • NER",
    telemetryActive: "NER Telemetry: Peitngor • 8 Jylla",
    gatewayConnected: "Gateway: Pyniasoh Bha",
    gatewayReconnecting: "Gateway: Dang pyniasoh pat...",
    sync: "Pyniahap Por",
    refresh: "Pynbha thymmai",
    commandDeck: "Command Deck",
    gisMap: "GIS Map",
    earlyWarning: "Maham Shwa Ka Por",
    fieldReview: "Bishar Report Na Madan",
    citizenPortal: "Portal ki Paidbah",
    fieldApp: "App ki Officer Madan",
    settings: "Ki Jingpynbeit",
    dbExplorer: "Database Peitngor",
    signIn: "Pynrung Kyrteng",
    signOut: "Mih Noh",
    threatLevel: "Kyrdan Jingma",
    activeAlerts: "Jingmaham ba Kyrkieh",
    criticalSectors: "Ki Dong ba Ma Bha",
    monitoredDistricts: "Ki District ba la Peitngor",
    evacuationDirective: "Hukum ban Phet na ki jaka ma",
    rainfallTelemetry: "Slap hapoh 24 kynta",
    recentAlerts: "Jingmaham ba dang shen",
    monitoredHotspots: "Ki Jaka ba Khyllem Khyndew",
    noActiveAlerts: "Ym don jingmaham ha kane ka por",
    safeThresholds: "Ka jingjur slap bad ka jingkhyllem ka dang biang ha ki pud ba shngain.",
    submitReport: "Ai Report Jingmaham",
    selectDistrict: "Jied ia ka District jong phi:",
    allDistricts: "Baroh 8 tylli ki District NER",
    severity: "Jingjur Jingma",
    critical: "MA BHA (CRITICAL)",
    high: "JUR (HIGH)",
    moderate: "MAR-PDENG (MODERATE)",
    low: "STIEP (LOW)",
    broadcastAlert: "Pynbna Jingmaham Kyrkieh",
    priority1Title: "Kyrdan Nyngkong: 8 ngut ki Commander",
    priority2Title: "Kyrdan Ba Ar: Ki Paidbah ba la register",
    emailAlerts: "Email Jingmaham",
    smsBroadcast: "SMS ba Kyrkieh",
    webRiskAlert: "Web App Jingmaham",
    dispatchedSuccess: "La pynbna suk ia ka jingmaham ha baroh ki channel"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('bhoomirakshak_lang') || 'English';
  });

  const handleSetLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem('bhoomirakshak_lang', lang);
    }
  };

  const t = (key, fallback = '') => {
    const currentDict = translations[language] || translations.English;
    return currentDict[key] || translations.English[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, availableLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'English',
      setLanguage: () => {},
      t: (k, def) => def || k,
      availableLanguages: ['English']
    };
  }
  return context;
}
